version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-todo_db}
      POSTGRES_USER: ${DB_USER:-todo_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-todo_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - BOT_TOKEN=${BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME:-todo_db}
      - DB_USER=${DB_USER:-todo_user}
      - DB_PASSWORD=${DB_PASSWORD:-todo_pass}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - API_URL=${API_URL:-http://backend:8000/api/}

  celery:
    build: ./backend
    command: celery -A todo_backend worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - BOT_TOKEN=${BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME:-todo_db}
      - DB_USER=${DB_USER:-todo_user}
      - DB_PASSWORD=${DB_PASSWORD:-todo_pass}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - API_URL=${API_URL:-http://backend:8000/api/}

  celery-beat:
    build: ./backend
    command: celery -A todo_backend beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - BOT_TOKEN=${BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME:-todo_db}
      - DB_USER=${DB_USER:-todo_user}
      - DB_PASSWORD=${DB_PASSWORD:-todo_pass}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - API_URL=${API_URL:-http://backend:8000/api/}

  bot:
    build: ./bot
    command: python main.py
    volumes:
      - ./bot:/app
    depends_on:
      - backend
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL:-http://backend:8000/api/}

volumes:
  postgres_data:
