# Generated by Django 5.2.3 on 2025-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_userprofile_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notifications_disabled',
            field=models.BooleanField(default=False, help_text='Отключить уведомления для этой задачи'),
        ),
    ]
